channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - snakemake
  - fastqc
  - umi_tools
  - cutadapt
  - star
  - samtools
  - java-jdk
  - ucsc-twobittofa
  - fastq-tools
  - bedtools
  - r
