sample_name: meCLIP

resources:
  threads: 11
  ram: 29

reads:
  ip:
    ip_read_1: reads/ip_read_1.fq
    ip_read_2: reads/ip_read_2.fq
  input:
    input_read_1: reads/input_read_1.fq
    input_read_2: reads/input_read_2.fq

species:
  name: homo_sapiens
  assembly: GRCh38
  release: 109

adapters:
  dna: 
    randomer_size: 10
  rna: 
    name: X1A
    sequence: AUAUAGGNNNNNAGAUCGGAAGAGCGUCGUGUAG